apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billing
  labels:
    app.kubernetes.io/name: billing
    app.kubernetes.io/part-of: taptech
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts: [billing.taptech.net]
      secretName: billing-tls
  rules:
    - host: billing.taptech.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: billing
                port:
                  name: http
