apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-prod-secret-stores
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: 'https://github.com/glawson6/taptech-gitops.git'
    targetRevision: main
    path: platform/external-secrets/stores/apps-prod
  destination:
    name: apps-prod
    namespace: external-secrets
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
