apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-prod-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: 'https://github.com/taptech/taptech-gitops.git'
    targetRevision: main
    path: platform/storage/apps-prod
  destination:
    name: apps-prod
    namespace: kube-system
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
